### ISSUE TITLE
Consider pivoting

### ISSUE THREAD

**Issue by astrojuanlu** [Juanlu001/pfc#1]
Googling "fenics portability" yielded this:

http://fenicsproject.org/pub/presentations/fenics14-paris/FEniCS14FlorianRathgeber.pdf

 At first glance:
- It's on GitHub https://github.com/firedrakeproject/firedrake
- Does not use CMake (really??), though they recommend https://github.com/firedrakeproject/firedrake/blob/master/scripts/firedrake-install
- Testing is easier http://www.firedrakeproject.org/download.html#testing-the-installation
- conda recipes already exist! https://github.com/gmarkall/firedrake-conda-recipes

Worth a look.

**Comment by astrojuanlu** [comment]
No.

**Comment by kynan** [comment]
@Juanlu001 Great you found my talk from FEniCS'14. What made you decide against Firedrake?

@dham @wence-

**Comment by astrojuanlu** [comment]
Hi @kynan, I appreciate your interest. Basically it's a matter of time constraints and motivation: on the one hand, I get the impression that Firedrake is still not super stable - not to say that FEniCS is, but at least I have the (slightly outdated but still useful) FEniCS book and lots of blog articles and support.

On the other hand, I spent some days trying to provide conda recipes hoping that it would be easier than with FEniCS, but it turned out Firedrake has its own set of problems.

https://github.com/gmarkall/firedrake-conda-recipes/pull/8

Still, I'll be watching very closely Firedrake progress because it has a lot of things that I find very appealing - specifically less C++ and more Python :)

**Comment by kynan** [comment]
That's probably a fair assessment! Note that Firedrake aims to be compatible where possible, so your FEniCS tutorials _should_ mostly apply. So keep watching it!
